(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

Parameter a: Z.

Parameter b: Z.

Axiom H : (b < 0%Z)%Z.

Parameter la: Z.

Axiom H1 : (la = (-a)%Z).

Parameter lb: Z.

Axiom H2 : (lb = (-b)%Z).

Parameter i: Z.

Parameter s: Z.

Axiom H3 : (s = (la * i)%Z).

Axiom H4 : (0%Z <= lb)%Z.

Axiom H5 : (0%Z <= i)%Z.

Axiom H6 : ~ (i < lb)%Z.

(* Why3 goal *)
Theorem VC_produit : ((a * b)%Z = s).
Proof.


Qed.

