#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 08 14:31:15 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto d0dc0ff160ee4403aa06191d00c554a4 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot diviseurClk_tb_behav xil_defaultlib.diviseurClk_tb -log elaborate.log"
xelab -wto d0dc0ff160ee4403aa06191d00c554a4 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot diviseurClk_tb_behav xil_defaultlib.diviseurClk_tb -log elaborate.log

