(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require int.Int.

(* Why3 assumption *)
Inductive ref (a:Type) :=
  | mk_ref : a -> ref a.
Axiom ref_WhyType : forall (a:Type) {a_WT:WhyType a}, WhyType (ref a).
Existing Instance ref_WhyType.
Arguments mk_ref {a}.

(* Why3 assumption *)
Definition contents {a:Type} {a_WT:WhyType a} (v:ref a) : a :=
  match v with
  | mk_ref x => x
  end.

Parameter r: Z.

Parameter x: Z.

Axiom H : ~ (x = 0%Z).

Parameter r1: Z.

Axiom H1 : (r1 = ((r + (2%Z * x)%Z)%Z - 1%Z)%Z).

Parameter x1: Z.

Axiom H2 : (x1 = (x - 1%Z)%Z).

(* Why3 goal *)
Theorem VC_carre : False.
Proof.


Qed.

