drop table Adresse if exists;
drop table Personne if exists;
create table Personne (
    id	      integer generated by default as identity (start with 1, increment by 1) not null,
    nom       varchar(30)      not null,
    prenom    varchar(30)      not null,
    adresses  integer array,
    primary key (id)
  );
  
create table Adresse (
    id	      integer generated by default as identity (start with 1, increment by 1) not null,
    adresse           varchar(100)      not null,
    primary key (id)
  );

commit;

