#!/bin/bash
ip link set dev eth0 up
echo 0 > /proc/sys/net/ipv4/ip_forward
ip a a 192.168.20.1/25 dev eth0 #adresse fixe pour la redirection de ports
ip r a default via 192.168.20.100 #et donc ne pas oublier la route par defaut
#dhclient eth0
service apache2 start
