<?xml version="1.0" encoding="UTF-8"?>
<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>demo</groupId>
	<artifactId>hello</artifactId>
	<version>1.0</version>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>17</maven.compiler.release>
	</properties>
	<dependencies>
		<!-- Apache ActiveMQ for JMS exercise -->
		<dependency>
			<groupId>org.apache.activemq</groupId>
			<artifactId>activemq-all</artifactId>
			<version>5.19.1</version>
		</dependency>
		<!-- Log4J is needed for ActiveMQ SLF4J -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.25.2</version>
		</dependency>
	</dependencies>
	<build>
		<!-- Sources and resources in src/ -->
		<sourceDirectory>${project.basedir}/src</sourceDirectory>
		<resources>
			<resource>
				<directory>${project.build.sourceDirectory}/resources</directory>
			</resource>
		</resources>
		<plugins>
			<!-- Formatter (mvn fmt:format) (Google Java Format) -->
			<plugin>
				<groupId>com.spotify.fmt</groupId>
				<artifactId>fmt-maven-plugin</artifactId>
				<version>2.24</version>
				<configuration>
					<filesNamePattern>.*\.java</filesNamePattern>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
