#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 08 15:07:01 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 6d88240a92c64e00831998612ef16cae --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot compteur_tb_behav xil_defaultlib.compteur_tb -log elaborate.log"
xelab -wto 6d88240a92c64e00831998612ef16cae --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot compteur_tb_behav xil_defaultlib.compteur_tb -log elaborate.log

