[general]
context=default
allowoverlap=no
udpbindaddr=0.0.0.0
tcpenable=no
tcpbindaddr=0.0.0.0
transport=udp
srvlookup=yes

[6001]
type=friend
host=dynamic
secret=6001

[6002]
type=friend
host=dynamic
secret=6002

[6003]
type=friend
host=dynamic
secret=6003

[6004]
type=friend
host=dynamic
secret=6004

[6005]
type=friend
host=dynamic
secret=6005
