# Interface
interface=enp1s0f1
# Adresses donnees
dhcp-range=120.0.64.2,120.0.71.254
# Adresse du routeur, route par defaut
dhcp-option=option:router,120.0.64.1
# Masque de sous-reseau /21
dhcp-option=option:netmask,255.255.248.0
# Adresse DNS
dhcp-option=option:dns-server,120.0.72.254