#!/bin/bash
ip link set dev eth0 up
ip link set dev eth1 up
ip addr add 192.168.20.100/25 dev eth0
ip addr add 201.201.201.1/27 dev eth1
echo 1 > /proc/sys/net/ipv4/ip_forward
ip route add default via 201.201.201.3
