webtalk_init -webtalk_dir /home/ave9761/git_perso/2a/archi/vivado/compteur/compteur.sim/sim_1/behav/xsim/xsim.dir/compteur_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  8 15:07:34 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "071fe380-58ee-4c50-9e54-1bf930fad845" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6d88240a92c64e00831998612ef16cae" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 24.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-14500" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1789.486 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122968_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3533561731 -regid "" -xml /home/ave9761/git_perso/2a/archi/vivado/compteur/compteur.sim/sim_1/behav/xsim/xsim.dir/compteur_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ave9761/git_perso/2a/archi/vivado/compteur/compteur.sim/sim_1/behav/xsim/xsim.dir/compteur_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ave9761/git_perso/2a/archi/vivado/compteur/compteur.sim/sim_1/behav/xsim/xsim.dir/compteur_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
