hostname ospfd
password zebra
log stdout

! Est ce qu'il faut mettre les interfaces dessus ?

router ospf
 ospf router-id 120.0.72.1
 network 120.0.72.0/25 area 0.0.0.0
 network 120.0.73.0/24 area 0.0.0.3

line vty
